from dataclasses import dataclass
from typing import List, Dict

@dataclass
class AIModel:
    id: str
    name: str
    category: str
    params: str
    min_vram_gb: float
    description: str
    tags: List[str]

# Complete official library of 239 models extracted live from https://ollama.com/library
MODEL_REGISTRY: List[AIModel] = [
    AIModel("llama3.1", "Llama3.1", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'llama3.1', '7b']),
    AIModel("deepseek-r1", "Deepseek R1", "Reasoning", "7B", 6.0, "Official Ollama reasoning model (7B)", ['reasoning', 'deepseek', '7b']),
    AIModel("nomic-embed-text", "Nomic Embed Text", "Embeddings", "Embedding", 0.8, "Official Ollama embeddings model (Embedding)", ['embeddings', 'nomic', 'embedding']),
    AIModel("llama3.2", "Llama3.2", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'llama3.2', '7b']),
    AIModel("gemma3", "Gemma3", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'gemma3', '7b']),
    AIModel("qwen2.5", "Qwen2.5", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'qwen2.5', '7b']),
    AIModel("qwen3", "Qwen3", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'qwen3', '7b']),
    AIModel("mistral", "Mistral", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'mistral', '7b']),
    AIModel("gemma2", "Gemma2", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'gemma2', '7b']),
    AIModel("llama3", "Llama3", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'llama3', '7b']),
    AIModel("gemma4", "Gemma4", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'gemma4', '7b']),
    AIModel("qwen2.5-coder", "Qwen2.5 Coder", "Coding", "7B", 6.0, "Official Ollama coding model (7B)", ['coding', 'qwen2.5', '7b']),
    AIModel("qwen3.5", "Qwen3.5", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'qwen3.5', '7b']),
    AIModel("llava", "Llava", "Vision", "7B", 6.0, "Official Ollama vision model (7B)", ['vision', 'llava', '7b']),
    AIModel("mxbai-embed-large", "Mxbai Embed Large", "Embeddings", "Embedding", 0.8, "Official Ollama embeddings model (Embedding)", ['embeddings', 'mxbai', 'embedding']),
    AIModel("gpt-oss", "Gpt Oss", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'gpt', '7b']),
    AIModel("qwen3-coder", "Qwen3 Coder", "Coding", "7B", 6.0, "Official Ollama coding model (7B)", ['coding', 'qwen3', '7b']),
    AIModel("gemma", "Gemma", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'gemma', '7b']),
    AIModel("phi4", "Phi4", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'phi4', '7b']),
    AIModel("qwen", "Qwen", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'qwen', '7b']),
    AIModel("glm-ocr", "Glm Ocr", "Vision", "7B", 6.0, "Official Ollama vision model (7B)", ['vision', 'glm', '7b']),
    AIModel("qwen3.6", "Qwen3.6", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'qwen3.6', '7b']),
    AIModel("bge-m3", "Bge M3", "Embeddings", "7B", 6.0, "Official Ollama embeddings model (7B)", ['embeddings', 'bge', '7b']),
    AIModel("qwen2", "Qwen2", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'qwen2', '7b']),
    AIModel("mistral-nemo", "Mistral Nemo", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'mistral', '7b']),
    AIModel("qwen3-vl", "Qwen3 Vl", "Vision", "7B", 6.0, "Official Ollama vision model (7B)", ['vision', 'qwen3', '7b']),
    AIModel("tinyllama", "Tinyllama", "General", "3B", 2.5, "Official Ollama general model (3B)", ['general', 'tinyllama', '3b']),
    AIModel("minicpm-v", "Minicpm V", "Vision", "3B", 2.5, "Official Ollama vision model (3B)", ['vision', 'minicpm', '3b']),
    AIModel("llama3.2-vision", "Llama3.2 Vision", "Vision", "7B", 6.0, "Official Ollama vision model (7B)", ['vision', 'llama3.2', '7b']),
    AIModel("qwen2.5vl", "Qwen2.5Vl", "Vision", "7B", 6.0, "Official Ollama vision model (7B)", ['vision', 'qwen2.5vl', '7b']),
    AIModel("deepseek-coder", "Deepseek Coder", "Coding", "7B", 6.0, "Official Ollama coding model (7B)", ['coding', 'deepseek', '7b']),
    AIModel("llama3.3", "Llama3.3", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'llama3.3', '7b']),
    AIModel("dolphin3", "Dolphin3", "Uncensored", "7B", 6.0, "Official Ollama uncensored model (7B)", ['uncensored', 'dolphin3', '7b']),
    AIModel("smollm2", "Smollm2", "General", "3B", 2.5, "Official Ollama general model (3B)", ['general', 'smollm2', '3b']),
    AIModel("deepseek-v3", "Deepseek V3", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'deepseek', '7b']),
    AIModel("qwen3-embedding", "Qwen3 Embedding", "Embeddings", "Embedding", 0.8, "Official Ollama embeddings model (Embedding)", ['embeddings', 'qwen3', 'embedding']),
    AIModel("olmo2", "Olmo2", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'olmo2', '7b']),
    AIModel("all-minilm", "All Minilm", "Embeddings", "3B", 2.5, "Official Ollama embeddings model (3B)", ['embeddings', 'all', '3b']),
    AIModel("codegemma", "Codegemma", "Coding", "7B", 6.0, "Official Ollama coding model (7B)", ['coding', 'codegemma', '7b']),
    AIModel("snowflake-arctic-embed", "Snowflake Arctic Embed", "Embeddings", "Embedding", 0.8, "Official Ollama embeddings model (Embedding)", ['embeddings', 'snowflake', 'embedding']),
    AIModel("mistral-small", "Mistral Small", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'mistral', '7b']),
    AIModel("deepseek-coder-v2", "Deepseek Coder V2", "Coding", "7B", 6.0, "Official Ollama coding model (7B)", ['coding', 'deepseek', '7b']),
    AIModel("granite3.1-moe", "Granite3.1 Moe", "Enterprise", "7B", 6.0, "Official Ollama enterprise model (7B)", ['enterprise', 'granite3.1', '7b']),
    AIModel("nemotron-3-super", "Nemotron 3 Super", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'nemotron', '7b']),
    AIModel("mixtral", "Mixtral", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'mixtral', '7b']),
    AIModel("mistral-small3.2", "Mistral Small3.2", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'mistral', '7b']),
    AIModel("minimax-m2.7", "Minimax M2.7", "General", "3B", 2.5, "Official Ollama general model (3B)", ['general', 'minimax', '3b']),
    AIModel("glm-5.1", "Glm 5.1", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'glm', '7b']),
    AIModel("llava-llama3", "Llava Llama3", "Vision", "7B", 6.0, "Official Ollama vision model (7B)", ['vision', 'llava', '7b']),
    AIModel("qwq", "Qwq", "Reasoning", "7B", 6.0, "Official Ollama reasoning model (7B)", ['reasoning', 'qwq', '7b']),
    AIModel("translategemma", "Translategemma", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'translategemma', '7b']),
    AIModel("gemma3n", "Gemma3N", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'gemma3n', '7b']),
    AIModel("smollm", "Smollm", "General", "3B", 2.5, "Official Ollama general model (3B)", ['general', 'smollm', '3b']),
    AIModel("dolphin-llama3", "Dolphin Llama3", "Uncensored", "7B", 6.0, "Official Ollama uncensored model (7B)", ['uncensored', 'dolphin', '7b']),
    AIModel("cogito", "Cogito", "Reasoning", "7B", 6.0, "Official Ollama reasoning model (7B)", ['reasoning', 'cogito', '7b']),
    AIModel("qwen3-coder-next", "Qwen3 Coder Next", "Coding", "7B", 6.0, "Official Ollama coding model (7B)", ['coding', 'qwen3', '7b']),
    AIModel("embeddinggemma", "Embeddinggemma", "Embeddings", "Embedding", 0.8, "Official Ollama embeddings model (Embedding)", ['embeddings', 'embeddinggemma', 'embedding']),
    AIModel("dolphin-mixtral", "Dolphin Mixtral", "Uncensored", "7B", 6.0, "Official Ollama uncensored model (7B)", ['uncensored', 'dolphin', '7b']),
    AIModel("llama4", "Llama4", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'llama4', '7b']),
    AIModel("moondream", "Moondream", "Vision", "7B", 6.0, "Official Ollama vision model (7B)", ['vision', 'moondream', '7b']),
    AIModel("phi4-reasoning", "Phi4 Reasoning", "Reasoning", "7B", 6.0, "Official Ollama reasoning model (7B)", ['reasoning', 'phi4', '7b']),
    AIModel("dolphin-mistral", "Dolphin Mistral", "Uncensored", "7B", 6.0, "Official Ollama uncensored model (7B)", ['uncensored', 'dolphin', '7b']),
    AIModel("sqlcoder", "Sqlcoder", "Coding", "7B", 6.0, "Official Ollama coding model (7B)", ['coding', 'sqlcoder', '7b']),
    AIModel("hermes3", "Hermes3", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'hermes3', '7b']),
    AIModel("dolphin-phi", "Dolphin Phi", "Uncensored", "7B", 6.0, "Official Ollama uncensored model (7B)", ['uncensored', 'dolphin', '7b']),
    AIModel("glm-4.7-flash", "Glm 4.7 Flash", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'glm', '7b']),
    AIModel("phi", "Phi", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'phi', '7b']),
    AIModel("granite-code", "Granite Code", "Coding", "7B", 6.0, "Official Ollama coding model (7B)", ['coding', 'granite', '7b']),
    AIModel("command-r", "Command R", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'command', '7b']),
    AIModel("magistral", "Magistral", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'magistral', '7b']),
    AIModel("granite4", "Granite4", "Enterprise", "7B", 6.0, "Official Ollama enterprise model (7B)", ['enterprise', 'granite4', '7b']),
    AIModel("ministral-3", "Ministral 3", "General", "3B", 2.5, "Official Ollama general model (3B)", ['general', 'ministral', '3b']),
    AIModel("yi", "Yi", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'yi', '7b']),
    AIModel("phi4-mini", "Phi4 Mini", "General", "3B", 2.5, "Official Ollama general model (3B)", ['general', 'phi4', '3b']),
    AIModel("qwen3.8", "Qwen3.8", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'qwen3.8', '7b']),
    AIModel("codestral", "Codestral", "Coding", "7B", 6.0, "Official Ollama coding model (7B)", ['coding', 'codestral', '7b']),
    AIModel("mistral-large", "Mistral Large", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'mistral', '7b']),
    AIModel("lfm2.5-thinking", "Lfm2.5 Thinking", "Reasoning", "7B", 6.0, "Official Ollama reasoning model (7B)", ['reasoning', 'lfm2.5', '7b']),
    AIModel("deepscaler", "Deepscaler", "Reasoning", "7B", 6.0, "Official Ollama reasoning model (7B)", ['reasoning', 'deepscaler', '7b']),
    AIModel("glm4", "Glm4", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'glm4', '7b']),
    AIModel("openthinker", "Openthinker", "Reasoning", "7B", 6.0, "Official Ollama reasoning model (7B)", ['reasoning', 'openthinker', '7b']),
    AIModel("lfm2", "Lfm2", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'lfm2', '7b']),
    AIModel("openhermes", "Openhermes", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'openhermes', '7b']),
    AIModel("codeqwen", "Codeqwen", "Coding", "7B", 6.0, "Official Ollama coding model (7B)", ['coding', 'codeqwen', '7b']),
    AIModel("qwen2-math", "Qwen2 Math", "Reasoning", "7B", 6.0, "Official Ollama reasoning model (7B)", ['reasoning', 'qwen2', '7b']),
    AIModel("neural-chat", "Neural Chat", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'neural', '7b']),
    AIModel("granite3.3", "Granite3.3", "Enterprise", "7B", 6.0, "Official Ollama enterprise model (7B)", ['enterprise', 'granite3.3', '7b']),
    AIModel("aya", "Aya", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'aya', '7b']),
    AIModel("yi-coder", "Yi Coder", "Coding", "7B", 6.0, "Official Ollama coding model (7B)", ['coding', 'yi', '7b']),
    AIModel("llama3-chatqa", "Llama3 Chatqa", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'llama3', '7b']),
    AIModel("devstral", "Devstral", "Coding", "7B", 6.0, "Official Ollama coding model (7B)", ['coding', 'devstral', '7b']),
    AIModel("llama-guard3", "Llama Guard3", "Enterprise", "7B", 6.0, "Official Ollama enterprise model (7B)", ['enterprise', 'llama', '7b']),
    AIModel("granite3.1-dense", "Granite3.1 Dense", "Enterprise", "7B", 6.0, "Official Ollama enterprise model (7B)", ['enterprise', 'granite3.1', '7b']),
    AIModel("granite3-dense", "Granite3 Dense", "Enterprise", "7B", 6.0, "Official Ollama enterprise model (7B)", ['enterprise', 'granite3', '7b']),
    AIModel("internlm2", "Internlm2", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'internlm2', '7b']),
    AIModel("aya-expanse", "Aya Expanse", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'aya', '7b']),
    AIModel("dolphincoder", "Dolphincoder", "Coding", "7B", 6.0, "Official Ollama coding model (7B)", ['coding', 'dolphincoder', '7b']),
    AIModel("samantha-mistral", "Samantha Mistral", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'samantha', '7b']),
    AIModel("llama3-gradient", "Llama3 Gradient", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'llama3', '7b']),
    AIModel("devstral-small-2", "Devstral Small 2", "Coding", "7B", 6.0, "Official Ollama coding model (7B)", ['coding', 'devstral', '7b']),
    AIModel("llama3-groq-tool-use", "Llama3 Groq Tool Use", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'llama3', '7b']),
    AIModel("granite3.2-vision", "Granite3.2 Vision", "Vision", "7B", 6.0, "Official Ollama vision model (7B)", ['vision', 'granite3.2', '7b']),
    AIModel("starling-lm", "Starling Lm", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'starling', '7b']),
    AIModel("granite3-moe", "Granite3 Moe", "Enterprise", "7B", 6.0, "Official Ollama enterprise model (7B)", ['enterprise', 'granite3', '7b']),
    AIModel("deepcoder", "Deepcoder", "Coding", "7B", 6.0, "Official Ollama coding model (7B)", ['coding', 'deepcoder', '7b']),
    AIModel("paraphrase-multilingual", "Paraphrase Multilingual", "Embeddings", "7B", 6.0, "Official Ollama embeddings model (7B)", ['embeddings', 'paraphrase', '7b']),
    AIModel("shieldgemma", "Shieldgemma", "Enterprise", "7B", 6.0, "Official Ollama enterprise model (7B)", ['enterprise', 'shieldgemma', '7b']),
    AIModel("reader-lm", "Reader Lm", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'reader', '7b']),
    AIModel("llama-pro", "Llama Pro", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'llama', '7b']),
    AIModel("bakllava", "Bakllava", "Vision", "7B", 6.0, "Official Ollama vision model (7B)", ['vision', 'bakllava', '7b']),
    AIModel("meditron", "Meditron", "Medical", "7B", 6.0, "Official Ollama medical model (7B)", ['medical', 'meditron', '7b']),
    AIModel("nomic-embed-text-v2-moe", "Nomic Embed Text V2 Moe", "Embeddings", "Embedding", 0.8, "Official Ollama embeddings model (Embedding)", ['embeddings', 'nomic', 'embedding']),
    AIModel("command-r-plus", "Command R Plus", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'command', '7b']),
    AIModel("mistral-small3.1", "Mistral Small3.1", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'mistral', '7b']),
    AIModel("nemotron-3-nano", "Nemotron 3 Nano", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'nemotron', '7b']),
    AIModel("exaone-deep", "Exaone Deep", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'exaone', '7b']),
    AIModel("deepseek-v3.1", "Deepseek V3.1", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'deepseek', '7b']),
    AIModel("nemotron-mini", "Nemotron Mini", "General", "3B", 2.5, "Official Ollama general model (3B)", ['general', 'nemotron', '3b']),
    AIModel("codegeex4", "Codegeex4", "Coding", "7B", 6.0, "Official Ollama coding model (7B)", ['coding', 'codegeex4', '7b']),
    AIModel("medllama2", "Medllama2", "Medical", "7B", 6.0, "Official Ollama medical model (7B)", ['medical', 'medllama2', '7b']),
    AIModel("mistral-openorca", "Mistral Openorca", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'mistral', '7b']),
    AIModel("nemotron3", "Nemotron3", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'nemotron3', '7b']),
    AIModel("opencoder", "Opencoder", "Coding", "7B", 6.0, "Official Ollama coding model (7B)", ['coding', 'opencoder', '7b']),
    AIModel("nemotron", "Nemotron", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'nemotron', '7b']),
    AIModel("reflection", "Reflection", "Reasoning", "7B", 6.0, "Official Ollama reasoning model (7B)", ['reasoning', 'reflection', '7b']),
    AIModel("athene-v2", "Athene V2", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'athene', '7b']),
    AIModel("qwen3-next", "Qwen3 Next", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'qwen3', '7b']),
    AIModel("megadolphin", "Megadolphin", "Uncensored", "7B", 6.0, "Official Ollama uncensored model (7B)", ['uncensored', 'megadolphin', '7b']),
    AIModel("solar-pro", "Solar Pro", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'solar', '7b']),
    AIModel("magicoder", "Magicoder", "Coding", "7B", 6.0, "Official Ollama coding model (7B)", ['coding', 'magicoder', '7b']),
    AIModel("exaone3.5", "Exaone3.5", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'exaone3.5', '7b']),
    AIModel("mathstral", "Mathstral", "Reasoning", "7B", 6.0, "Official Ollama reasoning model (7B)", ['reasoning', 'mathstral', '7b']),
    AIModel("nuextract", "Nuextract", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'nuextract', '7b']),
    AIModel("bespoke-minicheck", "Bespoke Minicheck", "General", "3B", 2.5, "Official Ollama general model (3B)", ['general', 'bespoke', '3b']),
    AIModel("duckdb-nsql", "Duckdb Nsql", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'duckdb', '7b']),
    AIModel("deepseek-ocr", "Deepseek Ocr", "Vision", "7B", 6.0, "Official Ollama vision model (7B)", ['vision', 'deepseek', '7b']),
    AIModel("firefunction-v2", "Firefunction V2", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'firefunction', '7b']),
    AIModel("rnj-1", "Rnj 1", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'rnj', '7b']),
    AIModel("minimax-m3", "Minimax M3", "General", "3B", 2.5, "Official Ollama general model (3B)", ['general', 'minimax', '3b']),
    AIModel("codebooga", "Codebooga", "Coding", "7B", 6.0, "Official Ollama coding model (7B)", ['coding', 'codebooga', '7b']),
    AIModel("goliath", "Goliath", "General", "70B", 42.0, "Official Ollama general model (70B)", ['general', 'goliath', '70b']),
    AIModel("kimi-k2.6", "Kimi K2.6", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'kimi', '7b']),
    AIModel("granite3.2", "Granite3.2", "Enterprise", "7B", 6.0, "Official Ollama enterprise model (7B)", ['enterprise', 'granite3.2', '7b']),
    AIModel("olmo-3", "Olmo 3", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'olmo', '7b']),
    AIModel("ornith", "Ornith", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'ornith', '7b']),
    AIModel("snowflake-arctic-embed2", "Snowflake Arctic Embed2", "Embeddings", "Embedding", 0.8, "Official Ollama embeddings model (Embedding)", ['embeddings', 'snowflake', 'embedding']),
    AIModel("r1-1776", "R1 1776", "Reasoning", "7B", 6.0, "Official Ollama reasoning model (7B)", ['reasoning', 'r1', '7b']),
    AIModel("deepseek-v4-flash", "Deepseek V4 Flash", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'deepseek', '7b']),
    AIModel("sailor2", "Sailor2", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'sailor2', '7b']),
    AIModel("granite4.1", "Granite4.1", "Enterprise", "7B", 6.0, "Official Ollama enterprise model (7B)", ['enterprise', 'granite4.1', '7b']),
    AIModel("tulu3", "Tulu3", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'tulu3', '7b']),
    AIModel("deepseek-v4-pro", "Deepseek V4 Pro", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'deepseek', '7b']),
    AIModel("mistral-medium-3.5", "Mistral Medium 3.5", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'mistral', '7b']),
    AIModel("granite-embedding", "Granite Embedding", "Embeddings", "Embedding", 0.8, "Official Ollama embeddings model (Embedding)", ['embeddings', 'granite', 'embedding']),
    AIModel("devstral-2", "Devstral 2", "Coding", "7B", 6.0, "Official Ollama coding model (7B)", ['coding', 'devstral', '7b']),
    AIModel("medgemma", "Medgemma", "Medical", "7B", 6.0, "Official Ollama medical model (7B)", ['medical', 'medgemma', '7b']),
    AIModel("glm-5.2", "Glm 5.2", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'glm', '7b']),
    AIModel("granite3-guardian", "Granite3 Guardian", "Enterprise", "7B", 6.0, "Official Ollama enterprise model (7B)", ['enterprise', 'granite3', '7b']),
    AIModel("llava-phi3", "Llava Phi3", "Vision", "7B", 6.0, "Official Ollama vision model (7B)", ['vision', 'llava', '7b']),
    AIModel("command-r7b", "Command R7B", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'command', '7b']),
    AIModel("phi4-mini-reasoning", "Phi4 Mini Reasoning", "Reasoning", "3B", 2.5, "Official Ollama reasoning model (3B)", ['reasoning', 'phi4', '3b']),
    AIModel("olmo-3.1", "Olmo 3.1", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'olmo', '7b']),
    AIModel("ornith-1.5", "Ornith 1.5", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'ornith', '7b']),
    AIModel("bge-large", "Bge Large", "Embeddings", "7B", 6.0, "Official Ollama embeddings model (7B)", ['embeddings', 'bge', '7b']),
    AIModel("smallthinker", "Smallthinker", "Reasoning", "7B", 6.0, "Official Ollama reasoning model (7B)", ['reasoning', 'smallthinker', '7b']),
    AIModel("alfred", "Alfred", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'alfred', '7b']),
    AIModel("kimi-k2.7-code", "Kimi K2.7 Code", "Coding", "7B", 6.0, "Official Ollama coding model (7B)", ['coding', 'kimi', '7b']),
    AIModel("command-a", "Command A", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'command', '7b']),
    AIModel("cogito-2.1", "Cogito 2.1", "Reasoning", "7B", 6.0, "Official Ollama reasoning model (7B)", ['reasoning', 'cogito', '7b']),
    AIModel("marco-o1", "Marco O1", "Reasoning", "7B", 6.0, "Official Ollama reasoning model (7B)", ['reasoning', 'marco', '7b']),
    AIModel("command-r7b-arabic", "Command R7B Arabic", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'command', '7b']),
    AIModel("functiongemma", "Functiongemma", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'functiongemma', '7b']),
    AIModel("muse-glimmer", "Muse Glimmer", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'muse', '7b']),
    AIModel("medgemma1.5", "Medgemma1.5", "Medical", "7B", 6.0, "Official Ollama medical model (7B)", ['medical', 'medgemma1.5', '7b']),
    AIModel("gpt-oss-safeguard", "Gpt Oss Safeguard", "Enterprise", "7B", 6.0, "Official Ollama enterprise model (7B)", ['enterprise', 'gpt', '7b']),
    AIModel("nemotron-3.5-lightning", "Nemotron 3.5 Lightning", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'nemotron', '7b']),
    AIModel("nemotron-cascade-2", "Nemotron Cascade 2", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'nemotron', '7b']),
    AIModel("lfm2.5", "Lfm2.5", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'lfm2.5', '7b']),
    AIModel("laguna-s-2.1", "Laguna S 2.1", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'laguna', '7b']),
    AIModel("laguna-xs-2.1", "Laguna Xs 2.1", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'laguna', '7b']),
    AIModel("mistral-large-3", "Mistral Large 3", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'mistral', '7b']),
    AIModel("nemotron-3-ultra", "Nemotron 3 Ultra", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'nemotron', '7b']),
    AIModel("kimi-k3", "Kimi K3", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'kimi', '7b']),
    AIModel("glm-5.3-flash", "Glm 5.3 Flash", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'glm', '7b']),
    AIModel("qwen3.8-flash-next", "Qwen3.8 Flash Next", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'qwen3.8', '7b']),
    AIModel("north-mini-code-1.0", "North Mini Code 1.0", "Coding", "3B", 2.5, "Official Ollama coding model (3B)", ['coding', 'north', '3b']),
    AIModel("minicpm-v4.6", "Minicpm V4.6", "Vision", "3B", 2.5, "Official Ollama vision model (3B)", ['vision', 'minicpm', '3b']),
    AIModel("minicpm-v4.5", "Minicpm V4.5", "Vision", "3B", 2.5, "Official Ollama vision model (3B)", ['vision', 'minicpm', '3b']),
    AIModel("laguna-xs.2", "Laguna Xs.2", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'laguna', '7b']),
    AIModel("glm-5.3", "Glm 5.3", "General", "7B", 6.0, "Official Ollama general model (7B)", ['general', 'glm', '7b']),
    AIModel("granite4.2", "Granite4.2", "Enterprise", "7B", 6.0, "Official Ollama enterprise model (7B)", ['enterprise', 'granite4.2', '7b']),
    AIModel("granite4.1-guardian", "Granite4.1 Guardian", "Enterprise", "7B", 6.0, "Official Ollama enterprise model (7B)", ['enterprise', 'granite4.1', '7b'])
]

def get_categories() -> List[str]:
    return sorted(list(set(m.category for m in MODEL_REGISTRY)))

def get_models_by_category(cat: str) -> List[AIModel]:
    return [m for m in MODEL_REGISTRY if m.category.lower() == cat.lower()]

def search_models(query: str) -> List[AIModel]:
    q = query.lower()
    return [
        m for m in MODEL_REGISTRY
        if q in m.id.lower() or q in m.name.lower() or q in m.description.lower() or any(q in t for t in m.tags)
    ]
def search_models(query: str) -> List[AIModel]:
    q = query.strip().lower()
    if not q:
        return []
    results = []
    for m in MODEL_REGISTRY:
        if q in m.id.lower() or q in m.name.lower() or q in m.category.lower() or any(q == t.lower() for t in m.tags):
            results.append(m)
    return results
